name: Build and Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Start SUT
        run: java -jar ./artifacts/app-order.jar &
        shell: bash

      - name: Run tests
        run: ./gradlew test

      - name: Publish Test Report (optional)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report
          path: build/reports/tests/test